### ISSUE TITLE
Status of cpp2numpy

### ISSUE THREAD

**Issue by dpiparo** [FredStober/cpp2numpy#1]
Hi Fred,

thanks for this nice package.
I just wanted to know what is the status of this package: is it actively maintained? Is it considered finished? Do you know if it has users?

Cheers,
    Danilo

**Comment by FredStober** [comment]
Hi Danilo,

a code project is never finished :)

The main function to write npz files - IO_npz::add_entry is pretty much finished. It could only be extended to support fortran_order numpy arrays for example.
It could probably be extended to also read npz files from C++, but with a lack of standardized multi-dimensional C++ array methods, this would imply defining a representation (when multi-dimensional span<T> is standardized, this would be a candidate ...).

However some convenience methods for integer arrays or python object serialization are not implemented - only float and double arrays (of arbitrary shape) are available.

The ROOT interface currently only has support for TH1D and TH2D (and TGraph but that is disabled). But since most people use the pyroot interface to directly get the histogram data nowadays, this part of the interface is not used that much anymore.
(see https://github.com/FredStober/plottools/blob/master/iotools_root.py)

**Comment by dpiparo** [comment]
I Fred, many thanks for the informations.
